### ISSUE TITLE
Neispravan ispis greške prilikom unosa polja "Prezime" i "username"

### ISSUE THREAD

**Issue by epajic16747** [SoftverInzenjeringETFSA/SI2016_TIM10#1]
Komponenta: novi-korisnik.js

Commit ID: 896350b 

Opis problema: Ukoliko se pogrešno unesu polja prezime, username i sl. greška za pogrešan unos se pojavljuje ispod polja gdje je ispravan unos. 

Koraci za reprodukciju problem:

- Pokrenuti aplikaciju
- Kliknuti na "Register" 
- Popuniti sva polja kao na slici 1.
- Kliknuti na “Registruj se”

Dobijeni rezultat: -Ime mora počinjati sa velikim slovom i ne smije sadržavati brojeve!!
                            -Prezime mora počinjati sa velikim slovom i ne smije sadržavati brojeve!!
                            -Unesite username!! 

Očekivani rezultat: -Prezime mora počinjati sa velikim slovom i ne smije sadržavati brojeve!!

Analogno i za polje username ako se ne unesete nista slika 2.
![registracja bug_3](https://cloud.githubusercontent.com/assets/17408033/26758124/933e8b46-48d5-11e7-9940-029c1f1af26e.png)
<p align="center">Slika 1. </p>

![registracja bug_5](https://cloud.githubusercontent.com/assets/17408033/26758380/b61796c4-48dc-11e7-93cd-1ef9e6d4a1d5.png)

<p align="center">Slika 2. </p>

**Comment by zdragnic** [comment]
![image](https://cloud.githubusercontent.com/assets/14365100/26762667/5ca47084-4946-11e7-88c6-d62e3d5a8db8.png)

![image](https://cloud.githubusercontent.com/assets/14365100/26762682/8ce0cf2c-4946-11e7-8793-7304ecb368d2.png) 

?
