### ISSUE TITLE
Korisnik dodaje objave, ali se stanje u bazi ne mijenja

### ISSUE THREAD

**Issue by eomanovic3** [SoftverInzenjeringETFSA/SI2016_TIM10#14]
**Komponente**: profil.js i baza tim10

**Opis problema**: Ukoliko korisnik objavi oglas, na profil.js će se to izmijeniti ali u bazi neće,tj broj objava se neće promijeniti i ostaje NULL.

**Koraci za reprodukciju problema:**
1.Registracija korisnika
2.Login korisnika
3.Objavi oglas 
4.Korisnik unese sve potrebne podatke za pravljenje oglasa

**Očekivani rezultat** : U bazi kod korisnika eomanovic, parametar broj_objava treba da bude 1.
**Dobijeni rezultat:** U bazi kod korisnika eomanovic, parametar broj_objava je NULL.
![prvi](https://cloud.githubusercontent.com/assets/17408022/26765677/24f6e6b8-4981-11e7-921d-2ee8c1a0e667.png)
Slika broj 1.
![drugi](https://cloud.githubusercontent.com/assets/17408022/26765678/26eb6cf0-4981-11e7-9126-8c2b762818ec.png)
Slika broj 2.

**Comment by zdragnic** [comment]
Ne smatram ovo bugom, na drugi nacin uzimam broj oglasa.
