### ISSUE TITLE
Neusaglašenost srsa i koda: unos fotografija

### ISSUE THREAD

**Issue by eomanovic3** [SoftverInzenjeringETFSA/SI2016_TIM10#15]
**Komponente:** profil.js ,advertise.js

**Opis problema:** Korisnik želi da doda slika sa svog direktorija na oglas, ali u polju slika to mu nije omogućeno. Korisnik očekuje mogućnost upload-a, kao što je to navedeno u srs-u, ali omogućen je unos slike samo putem url-a. Na slici 1. je prikazan dio srs-a u kojem se kaže da se traži ispravan format slike, tj tip jpeg,png i slično, dok na slici 2. je  prikazan unos kakav je prikazan korisniku na advertise.js. 

**Koraci za reprodukciju problema:**
1.Registracija korisnika
2.Login korisnika
3.Objavi oglas
4.Korisnik unese sve potrebne podatke za pravljenje oglasa
5.Prilikom unosa fotografije pokušava izvršiti upload slike

**Očekivani rezultat** : Treba omogućiti upload fotografije ispravnog formata
**Dobijeni rezultat:** Polje za unos fotografije očekuje tekstualni input
![image](https://cloud.githubusercontent.com/assets/17408022/26765847/ca238da0-4984-11e7-8148-e355c20d0152.png)
Slika broj 1
![image](https://cloud.githubusercontent.com/assets/17408022/26765849/d426111a-4984-11e7-87cc-d5341d5b0493.png)
Slika broj 2

**Comment by zdragnic** [comment]
Proslo 23:59 :)
