### ISSUE TITLE
Ukoliko se na nekim poljima izvrši pogrešan unos podataka, a zatim isti isprave nije moguće kreirati korisnika

### ISSUE THREAD

**Issue by epajic16747** [SoftverInzenjeringETFSA/SI2016_TIM10#2]
Komponente: novi-korisnik.js i register.js

Commit ID: 896350b 

Opis problema: Ukoliko se prezime, username i password pogrešno unesenu, a zatim isprave nije moguće kreirati korisnički račun. Nije potrebno da se pogrešno pogrešno unesu sva tri polja nego je dovoljno barem jedno da se izazove ova greška 

Koraci za reprodukciju problem:

- Pokrenuti aplikaciju
- Kliknuti na "Register" 
- Popuniti sva polja kao na slici 1.
- Kliknuti na “Registruj se”
- Ispraviti polje "prezime kao na slici 2.

Dobijeni rezultat: -Ime mora počinjati sa velikim slovom i ne smije sadržavati brojeve!!
                            -Prezime mora počinjati sa velikim slovom i ne smije sadržavati brojeve!!
                            -Unesite username!! 

Očekivani rezultat: -Kreiran racun!

![registracja bug_3](https://cloud.githubusercontent.com/assets/17408033/26758124/933e8b46-48d5-11e7-9940-029c1f1af26e.png)
<p align="center">Slika 1. </p>

![registracja bug_4](https://cloud.githubusercontent.com/assets/17408033/26758192/635fe418-48d7-11e7-9147-8b8e5a1b22a8.png)

<p align="center">Slika 2. </p>

Napomena: Takodjer se zna desiti isti problem ako se password pogrešno unese, a zatim se doda ono što se traži

**Comment by zdragnic** [comment]
![image](https://cloud.githubusercontent.com/assets/14365100/26762738/8741c746-4947-11e7-975b-dd31338fd487.png)

![image](https://cloud.githubusercontent.com/assets/14365100/26762740/90eaef02-4947-11e7-9f81-8a72a452c051.png)

**Comment by epajic16747** [comment]
Fali kod mene nesto, ali kako je iza 12 nema veze.
