### ISSUE TITLE
 Brisanje korisničkog računa - dugme za brisanje

### ISSUE THREAD

**Issue by vildanap** [SoftverInzenjeringETFSA/SI2016_TIM10#8]
**Komponenta**:  rentals.js
**Opis problema:**

Nakon prijave korisnika, na naslovnoj stranici se prikazuju button-i "Obriši profil" i "Objavi novi oglas". Ukoliko korisnik ode na bilo koju drugu podstranicu, povratkom na naslovnu stranicu button-i se više neće prikazati.

**Koraci za reprodukciju problema:**
- Pokrenuti aplikaciju
- Login korisnika
- Rezultat (slika 1.)
- Kliknuti na panelu na "Advertise"
- Klinuti na panelu na "Nekretnine"
- Rezultat (slika 2.)

**Dobijeni rezultat**: Naslovna stranica bez dugmadi "Obriši profil" i "Objavi novi oglas".
**Očekivani rezultat**: Naslovna stranica sa dugmadima: "Obriši profil" i "Objavi novi oglas".

Slika 1. 
![screenshot_6](https://cloud.githubusercontent.com/assets/17410223/26762762/e2444b5a-4947-11e7-907c-24baf8969991.png)
Slika 2.
![screenshot_7](https://cloud.githubusercontent.com/assets/17410223/26762766/fe12369e-4947-11e7-85fe-d8587a793e09.png)

**Comment by zdragnic** [comment]
![image](https://cloud.githubusercontent.com/assets/14365100/26762793/5cc97670-4948-11e7-812d-e109e2f90472.png)

![image](https://cloud.githubusercontent.com/assets/14365100/26762797/6d1d7b34-4948-11e7-9b95-dea9dccd7cab.png)

Razlicite podstranice, razlicit izgled.
